language: node_js
node_js:
  - 10.15.0
cache:
  directories:
    - node_modules
branches:
  only:
    - master
env:
  global:
    # AWS_ACCESS_KEY
    - secure: sdTCdtPsgfuA7uLGviM2v8wpSHhEdlGRpHXYitfEOCPUBXA801FYUkvPCZIeLCarY1hoJCAvTkrZlmrqbrc15RAgysPGyUrEopyC9AH8etVmGIs15gW/jap0+bbPnvcs9VtaafpPUjkDYKj/ycBYqbm9Qa/KZ1GK/VE+zspbrXxwUjH/MVJdfaixiVJgNTJgVe876e5PfBEEdFjAhTXntSlUM3GNvoBUlMnTsx2qiYYqWLr2TaPU3g3KRAhCUW4v37TEEPebHfQQkU2dAaKUbDdLlX3DjdwLJRdkGTU+eWj0Z6yq+g0pdoy+xH8z1DHQ4OqhMBWBHjN2bMsa3TAmuHRL+RBacyX2cygiN+RwQsr7MsnF17Cp6nh8PPO2WryIzgfhhBLpgAlmtaDvI8q9mkv9IcDoo+T5Oqot6tJM79S3vnmufAZmb6KkL5Wdv2MRfIu4ukztymkQ2USVJGGAFfUqk7eUrFZ+pzdWMGh0giI5BlweDcZK+Pg+fclj71RhBBpbsslFEXEpMkFrOW/1xr5OnFwQd3PCjtwpHKVK7I1f+eSUe0fmgGWmJnRwNFrF2mnMzHbRf85/k1oekYUb4QGQhSVs4Wb8A0Hoj172wBYkUM+gEqe4Asfn2psRw66nXaTWboiW2ATA+z9NYgLEqERxBpV23bM/ZttI3tLC0u8=
    # AWS_SECRET_ACCESS_KEY
    - secure: Br3SNTg5m3sk69L/g2br3le/7viR1qFpqNSWah48Ndf+ZBosp6z7gzQteagYpdvVcf8qEqHx0icyuAk7FMBSuXlJHUrAKsOeRH79CfK2iM42Emj1Ho2zLmc6dQ5Zhum2yskG3CN2EL3uFet6ltVB8u3t9La9jxHtO/ZLiA0rNjFpxc2i1gsQAveYLFneKhd10XuyyFIf3ARieroe2E/vnrEbCmipl9KN6VkV7VjgMIVdemj3jeg7SCV0IQDwMP5VIUNLHM7ZZ0Y5/qlnA+F12RxwJ+ljIDzz//0EUpcIhEmdB0tHbH/awd/kh1BgkELzvLr6ydXbNEnfNTDCVK4uFiRgWkcTYo6F22KxgJdZ60QS0wOtMRaKRWwdX9Zw3/V2BNOnQl5R2UPodkUFETYrhDzGX/vRzgbWAzHXMJv2ufSElZzjEaY+ootqkZ/tpPqQQYetIknvXOMZq6bH4XnS+Rsec2KpU3YFtnfBZDwXhGNlfl3wYebNCJ3tkSKT4IeG9tTWl3hwaNf2WYOcb9lX/p1p6ObmGqAuBpCWjG2/eiYmWgLKPUnPXe064h9GUEejYvy1pYc+KIFev5O3SzklzHE8Av7BlIUywlA7uU1NFeC+qnKfcKFmD5FDRsneidr/i8f3QN9sKigRUAWoDDI8bR2CAxLU/DXI/Qbm9XCqtpQ=
    # AWS_CLOUDFRONT_DIST_ID
    # - secure: OzoAhLgbTx1eVeldOnKRUrDO61JRp2pe4Cxzr4zlgIzp3QXa+B/kbVueXo6gXSmP7qErz5AIbOIccwhAdRmWdAJYHgR+be8+P/b+lkOeomxY8TPSsaHaA+I+RX5YHFnLpe2+MWgDwLhoMNBA3B2097rykjQ73sCChYg10qssZAIRX1WMxh/JRx6NEclUwZrEVsYcH8uVsP5ryuU6m5huazeAgJJugMcQUJQ7pXMuRpN7IunIsVkCh3WHPdKSL/r8SJCCMMbuFVhzKrF50Uluf41tuQk4V7KklYIzZdbr3UOWLKe+YkhNEAw/ysH+Z/keUSkwo0dHEHjR5tE6P8iYbZ3IeU9sXOicj2pcyM/Bh39hDj+gfz8tK291KgZLaK1+9Mm04pG4WFboXMhTTI13p4WNrje0NYhOpstrdNgNGITFCt7Qnew9BbAqnIh00rzsP8elw4EKD3JzuMUvjlPohahYYCd1LSpSudvvQ35zUQ/y5h5eEtW2uS7v6wq6cZz897N283TqoNFIDhG8+bIhouVNNirkA+FFX3e7DdpTGgSg3jlzE0ITZ666XfhiZi4vE2JK9H5sOZM7Z4kxcYj6aWKxlnoB5GBoTH75Ry6KTp8HV+CKjgy2VEOz0BbGiU0V07MNG39Sz4uiTK1pysag3pcaSe0hQejQVVjsdpLOQHI=
# install:
#   - npm install
#   - npm install -g travis-ci-cloudfront-invalidation
before_deploy:
  - npm run build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: us-east-1
  bucket: lost-cousins-v2
  local-dir: build
  skip_cleanup: true
  acl: public_read
  on:
    repo: thomasdashney/lc-web
    branch: master
after_deploy:
# -  travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY -s $AWS_SECRET_ACCESS_KEY -c $AWS_CLOUDFRONT_DIST_ID -i '/index.html' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST
